### ISSUE TITLE
Why is there always absolute error in the output of the c version and the python version ?

### ISSUE THREAD

**Issue by orestonce** [f0uriest/keras2c#10]

**Comment by orestonce** [comment]
And how to reduce the error to 0 ?

**Comment by f0uriest** [comment]
Not sure what you mean, but by default the code will create a test ``main`` function that will compare the ouputs of the C version to that of the python version and report the difference, is that what you mean?

In general the error will not be zero due to the use of different math operations and different compiler optimizations, but it should generally be very low error (around machine precision)

**Comment by orestonce** [comment]
Okay, got it.
